RESfulウェブサービス用テストFW実装
nablarch/nablarch-testing-rest pull request #1
Opened 2020-05-28 11:06 UTC by kumagoro1202

2020-06-05 12:01 UTC, backpaper0 requested changes

2020-06-05 12:01 UTC, backpaper0 commented on src/main/java/nablarch/test/core/http/RestTestSupport.java
> +            FileUtil.closeQuietly(out);
`FileUtil.closeQuietly(is, out);`で1行にまとめられます。

2020-06-05 12:01 UTC, backpaper0 commented on src/main/java/nablarch/test/core/http/RestTestSupport.java
> +            return new String(out.toByteArray(), "UTF-8");
`out.toString("UTF-8");`で良いのでは。

2020-06-05 12:01 UTC, backpaper0 commented on src/main/java/nablarch/test/core/http/RestTestSupport.java
> +            throw new IllegalArgumentException(concat(
`+`演算子で結合すれば良いです。

2020-06-05 12:01 UTC, backpaper0 commented on src/main/java/nablarch/test/core/http/RestTestSupport.java
> +        List<ResourceLocator> basePaths = new ArrayList<ResourceLocator>();
`baseDirs.length`で初期化できます。

```
new ArrayList<ResourceLocator>(baseDirs.length);
```

2020-06-05 12:01 UTC, backpaper0 commented on src/main/java/nablarch/test/core/http/RestTestSupport.java
> +            basePaths.add(buildWarDirUri(dir));
`buildWarDirUri`はここからしか呼び出されていないし、メソッドの内容もかなり少ないのでわざわざメソッドに切り出す必要はないと思いました。

2020-06-05 12:01 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +        getHeaderMap().put("Content-Length", String.valueOf(bodyStr.getBytes().length));
GETリクエストのようにリクエストボディを持たない場合を考慮してください。
そもそも`Content-Length`ヘッダが不要なはずです。

2020-06-05 12:01 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +                bodyStr = encodedParams;
クエリ文字列とリクエストボディは排他的な存在ではないので違和感があります。

例えば次のようなコードを実行したとき、

```
final RestMockHttpRequest req = new RestMockHttpRequest(
		Collections.singletonList(new MockWriter()), "testType");
req.setMethod("POST");
req.setRequestPath("/test");
req.setParam("foo", "hello");
req.setParam("bar", "world");
req.setContentType("text/plain");
req.setBody("xyz");
final String s = req.toString();
System.out.println(s);
```

こうなります。

```
POST /test HTTP/1.1
Content-Length: 19
Content-Type: text/plain

bar=world&foo=hello
```

コードから直感的に期待される結果はこうかな、と。

```
POST /test?bar=world&foo=hello HTTP/1.1
Content-Length: 3
Content-Type: text/plain

xyz
```

ちなみにこのようなコードにすれば上記のHTTPレスポンスを得られます。

```
final RestMockHttpRequest req = new RestMockHttpRequest(
		Collections.singletonList(new MockWriter()), "testType");
req.setMethod("POST");
req.setRequestPath("/test?foo=hello&bar=world");
req.setContentType("text/plain");
req.setBody("xyz");
final String s = req.toString();
System.out.println(s);
```

なので`setParam`と`setBody`が排他的なことが問題ではなく、コードと結果が直感に反していることを改善して欲しいです（例えば`setParam`と`setBody`が両方とも設定されていたら例外にするとかもダメではない）。

2020-06-05 12:01 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +            String[] values = param.getValue();
ここも`Iterator`を使った方がわかりやすいと思います。

```
Iterator<String> values = Arrays.asList(param.getValue()).iterator();
while (values.hasNext()) {
    buffer.append(name)
            .append("=")
            .append(encode(values.next()));
    if (values.hasNext()) {
        buffer.append("&");
    }
}
```

2020-06-05 12:01 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +        Matcher matcher = URI_PATTERN.matcher(uri);
`indexOf`と`substring`で事足りる気がします。

2020-06-05 12:01 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +            writeBody(bodyWriter);
この`StringWriter`の使い方だと`HttpBodyWriter`が`Writer`を受け取る意味がありません。

`Content-Length`を計算するためにこのようなコードになったのだと思いますが、そのために`Writer`を受け取る仕様を活かせないのであればいっそ`Writer`を受け取らず、単に`String`を返すようにすれば良いです。

2020-06-05 12:01 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +            if (httpBodyWriter.isWritable(body, getContentType())) {
`getContentType`は`Map`から`Content-Type`を取得するような処理をしているので、ループの外で行って変数に保持する方が効率がいいですね。
単なるgetterならこのコードでも良かったです。

2020-06-05 12:01 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/StringHttpBodyWriter.java
> +                        || contentType.toLowerCase().contains("application/json"));
`contentType`のチェックはしなくても良いと思います。
例えば`HttpBodyWriter`を用意するまでもなく雑にCSV（`text/csv`）を書き出したいなんてこともあると思うので。

2020-06-05 12:01 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/JacksonHttpBodyWriter.java
> +        return !(body instanceof String) && contentType.toLowerCase().contains("application/json");
`String`を除く必要はありますか？

それと`Content-Type`のチェックをするのに`contains`は不適切ですね。例えば（極端な例ですが）`application/json-p`が設定されていると困るな、とか。

`ContentType`クラスを作って簡単にチェックできるようにしてもいいかもですね。

2020-06-08 04:29 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +                bodyStr = encodedParams;
FormをPOSTする際にsetParamしたパラメータをボディに持たせたいので「setParamとsetBodyが両方とも設定されていたら例外にする」で対応します。

2020-06-08 04:37 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/JacksonHttpBodyWriter.java
> +        return !(body instanceof String) && contentType.toLowerCase().contains("application/json");
Stringを除いたのはStringHttpBodyWriterと重複すると思ったからでした。どちらでwriteしてもいいのでStringの判定を削除しました。
Content-TypeのチェックはContentTypeクラスを作りました。

2020-06-09 04:34 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/RestTestSupport.java
> +            FileUtil.closeQuietly(out);
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/26354bd1ab6e6169c8149d7f9d815668a50ea2c1#diff-8a25fd180bc2a7bfe6b07302b1527e34R282

1行にまとめました。

2020-06-09 04:35 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/RestTestSupport.java
> +            return new String(out.toByteArray(), "UTF-8");
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/26354bd1ab6e6169c8149d7f9d815668a50ea2c1#diff-8a25fd180bc2a7bfe6b07302b1527e34R280

2020-06-09 04:35 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/RestTestSupport.java
> +            throw new IllegalArgumentException(concat(
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/26354bd1ab6e6169c8149d7f9d815668a50ea2c1#diff-8a25fd180bc2a7bfe6b07302b1527e34R106-R108

2020-06-09 04:36 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/RestTestSupport.java
> +        List<ResourceLocator> basePaths = new ArrayList<ResourceLocator>();
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/26354bd1ab6e6169c8149d7f9d815668a50ea2c1#diff-8a25fd180bc2a7bfe6b07302b1527e34R207

2020-06-09 04:36 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/RestTestSupport.java
> +            basePaths.add(buildWarDirUri(dir));
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/26354bd1ab6e6169c8149d7f9d815668a50ea2c1#diff-8a25fd180bc2a7bfe6b07302b1527e34R209-R215

2020-06-09 04:37 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +        getHeaderMap().put("Content-Length", String.valueOf(bodyStr.getBytes().length));
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/26354bd1ab6e6169c8149d7f9d815668a50ea2c1#diff-57b42d271df0c95b023bff9b4d1a28f7R128

2020-06-09 04:37 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +                bodyStr = encodedParams;
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/26354bd1ab6e6169c8149d7f9d815668a50ea2c1#diff-57b42d271df0c95b023bff9b4d1a28f7R105-R107

2020-06-09 04:38 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +            String[] values = param.getValue();
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/26354bd1ab6e6169c8149d7f9d815668a50ea2c1#diff-57b42d271df0c95b023bff9b4d1a28f7R166-R174

2020-06-09 04:38 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +        Matcher matcher = URI_PATTERN.matcher(uri);
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/26354bd1ab6e6169c8149d7f9d815668a50ea2c1#diff-57b42d271df0c95b023bff9b4d1a28f7R189-R207

2020-06-09 04:39 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +            writeBody(bodyWriter);
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/d870e0327a55e9548604b34b546119388502688b

https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/3bb2d92b184cf26e7d2b56feaed03673b83817a2

2020-06-09 04:41 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +            if (httpBodyWriter.isWritable(body, getContentType())) {
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/26354bd1ab6e6169c8149d7f9d815668a50ea2c1#diff-57b42d271df0c95b023bff9b4d1a28f7R243-R247

https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/26354bd1ab6e6169c8149d7f9d815668a50ea2c1#diff-57b42d271df0c95b023bff9b4d1a28f7R259

2020-06-09 04:41 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/StringHttpBodyWriter.java
> +                        || contentType.toLowerCase().contains("application/json"));
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/3bb2d92b184cf26e7d2b56feaed03673b83817a2#diff-c2b8e937b369c263cc29494844f2cebaR10

2020-06-09 04:41 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/JacksonHttpBodyWriter.java
> +        return !(body instanceof String) && contentType.toLowerCase().contains("application/json");
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/3bb2d92b184cf26e7d2b56feaed03673b83817a2#diff-b8471c9320ff88d602823a26044f1b47R35

2020-06-09 08:14 UTC, backpaper0 requested changes

2020-06-09 08:14 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/ContentType.java
> +        if (second.toUpperCase().startsWith("CHARSET")) {
一般的にMimeTypeのパラメーターは小文字で書かれることが殆どだと思います。
`toLowerCase`の方が違和感がないです。

2020-06-09 08:14 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/ContentType.java
> +    public boolean is(String mediaType) {
このメソッドは`ContentType`を受け取る方が自然だと思います。

2020-06-09 08:14 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/ContentType.java
> +    public String getMediaType() {
`getMediaType`、`getCharset`、`getBoundary`ってテストコードでしか使われていないように見えるんですが、その理解で合っていますか？

そうだとしたらこれらのメソッドの存在はとても微妙です。
アサーションのために定義をするならアクセサではなく`equals`（と`hashCode`）の方が良いです。

2020-06-09 08:14 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/ContentType.java
> +    public String getMediaType() {
あと、そうであれば`charset`と`boundary`ってわざわざパースしなくても良いんじゃないかなぁ。

2020-06-09 08:14 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/HttpBodyWriter.java
> +     * @param contentType Content-Type
`@return`がないですね。

2020-06-09 08:14 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/HttpBodyWriter.java
> +    String writeValueAsString(Object body, ContentType contentType);
シグネチャが変わってメソッド名に違和感を覚えるようになりました。

Jacksonの`ObjectMapper`にも`writeValueAsString`というメソッドはありますが、あれは`writeValue`というメソッドがまずあって、それの`String`を返すバージョンとして捉えると違和感は少ないです。
こちらはこのメソッドだけなので違和感があります。
インターフェース名も併せて考え直してみてください。

2020-06-09 08:14 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +    public RestMockHttpRequest setRequestUri(String requestPath) {
`setParam`や`setCookie`も`RestMockHttpRequest`を返すようoverrideしておいた方が便利だと思いました。
特に`setParam`。

2020-06-09 08:14 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +            getHeaderMap().put("Content-Length", String.valueOf(contentLength));
`toString`で状態を変更するのはよくないですね。
空の`Map`インスタンスを用意してそこに`getHeaderMap`を`putAll`してから`Cotnent-Length`を設定するのが良いと思います。

あと明示的に`Content-Length`を設定しても上書きされるんですよね？
そこに対しては何かケアしておいた方が良いですね。

2020-06-09 08:14 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +            return "";
パラメーターがないなら`null`を返した方が自然です。

2020-06-09 08:14 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +    private String urlEncode(String uri) {
[java.net.URI.toASCIIString](https://docs.oracle.com/javase/jp/8/docs/api/java/net/URI.html#toASCIIString--)で事足りる気がしてきました。

2020-06-09 08:14 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +            return detectedHttpBodyWriter.writeValueAsString(body, contentType);
`body`の`null`チェックをした方が良いと思います。

2020-06-09 08:14 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +            return "";
`body`が無いのであれば`null`を返す方が自然です。

2020-06-10 06:30 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/ContentType.java
> +        if (second.toUpperCase().startsWith("CHARSET")) {
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/f59e140fb01fd2bb290958dcb5bb2182e9b2c4f4#diff-c71d1ec016afd364224d9cd82214ae31

2020-06-10 06:31 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/ContentType.java
> +    public boolean is(String mediaType) {
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/f59e140fb01fd2bb290958dcb5bb2182e9b2c4f4#diff-c71d1ec016afd364224d9cd82214ae31

2020-06-10 06:31 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/ContentType.java
> +    public String getMediaType() {
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/f59e140fb01fd2bb290958dcb5bb2182e9b2c4f4#diff-c71d1ec016afd364224d9cd82214ae31

2020-06-10 06:32 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/HttpBodyWriter.java
> +    String writeValueAsString(Object body, ContentType contentType);
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/f59e140fb01fd2bb290958dcb5bb2182e9b2c4f4

2020-06-10 06:32 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/HttpBodyWriter.java
> +     * @param contentType Content-Type
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/f59e140fb01fd2bb290958dcb5bb2182e9b2c4f4#diff-103bfda101b859c7ce20541f451869daR22

2020-06-10 06:33 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/ContentType.java
> +    public String getMediaType() {
MIMEタイプだけを保持して同値の評価をするクラスにしました。

2020-06-10 06:33 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +    public RestMockHttpRequest setRequestUri(String requestPath) {
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/9dbb0712544ef8914fab26b1dcfe39c0daf28a99#diff-57b42d271df0c95b023bff9b4d1a28f7R103-R117

2020-06-10 06:34 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +    public RestMockHttpRequest setRequestUri(String requestPath) {
setHttpVersionやsetBodyReaderは使用頻度が低そうなのでoverrideしてません。

2020-06-10 06:36 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +            getHeaderMap().put("Content-Length", String.valueOf(contentLength));
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/9dbb0712544ef8914fab26b1dcfe39c0daf28a99#diff-57b42d271df0c95b023bff9b4d1a28f7R129

https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/9dbb0712544ef8914fab26b1dcfe39c0daf28a99#diff-57b42d271df0c95b023bff9b4d1a28f7R170-R190

2020-06-10 06:36 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +            getHeaderMap().put("Content-Length", String.valueOf(contentLength));
`Content-Length`が設定されていて算出した値と異なる場合例外を送出するようにしました。

2020-06-10 06:37 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +            return "";
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/9dbb0712544ef8914fab26b1dcfe39c0daf28a99#diff-57b42d271df0c95b023bff9b4d1a28f7R199

2020-06-10 06:37 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +    private String urlEncode(String uri) {
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/941215d037ba7ee6233e7ad3c0a4cbd2de5977c3#diff-57b42d271df0c95b023bff9b4d1a28f7R232

2020-06-10 06:38 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +            return detectedHttpBodyWriter.writeValueAsString(body, contentType);
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/9dbb0712544ef8914fab26b1dcfe39c0daf28a99#diff-57b42d271df0c95b023bff9b4d1a28f7R282

2020-06-10 06:39 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +            return "";
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/9dbb0712544ef8914fab26b1dcfe39c0daf28a99#diff-57b42d271df0c95b023bff9b4d1a28f7R282

2020-06-11 00:36 UTC, backpaper0 requested changes

2020-06-11 00:36 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/MediaType.java
> +        mediaType = parts[0].trim();
ここで`toLowerCase`しておけば各メソッドでcaseに注意する必要がなくなります。

2020-06-11 00:36 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/JacksonBodyConverter.java
> +    public static final MediaType CONVERTIBLE_TYPE = new MediaType("application/json");
`private`で良いのでは？

変数のスコープはむやみに広くしない方が良いです。

2020-06-11 00:36 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/JacksonBodyConverter.java
> +        configure(objectMapper);
コンストラクタ内から他のメソッドを呼ぶのは、継承が絡むとバグりやすくなるので個人的にはバッドプラクティスだと感じています。

こんな感じにする方が拡張性も高くて良いと思います。

```
    public JacksonBodyConverter() {
    	this(new DefaultObjectMapperFactory());
    }

    public JacksonBodyConverter(ObjectMapperFactory factory) {
        objectMapper = factory.create();
    }

    public interface ObjectMapperFactory {
    	ObjectMapper create();
    }
    
    public static class DefaultObjectMapperFactory implements ObjectMapperFactory {
		@Override
		public ObjectMapper create() {
			ObjectMapper objectMapper = new ObjectMapper();
			objectMapper.getFactory().configure(JsonWriteFeature.ESCAPE_NON_ASCII.mappedFeature(), true);
			return objectMapper;
		}
    }
```

2020-06-11 00:36 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/BodyConverter.java
> +     * @return ボディを表す文字列
「ボディを表す」という表現がここだけ出てきて違和感があります。
単に「bodyを変換した文字列」とかで良いのでは。

2020-06-11 00:36 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +    public MediaType getMediaType() {
`MediaType`はテスティング内部で使用しているものであって、テストコードを書く人には不要ではないですか？

2020-06-11 00:36 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +    public RestMockHttpRequest setRequestUri(String requestPath) {
> 使用頻度が低そうなのでoverrideしてません。

overrideしない根拠としては弱いですね。
一貫性も大事にしてください。

2020-06-11 00:36 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +    private String urlEncode(String uri) {
`toString`内でURLを組み立てていますが、その後に`java.net.URI.toASCIIString`したらもっと楽になりそうだと思ったんですが、どうですか？

2020-06-11 02:29 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/MediaType.java
> +        mediaType = parts[0].trim();
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/a34a6855a509aeef0e7355d5aa097049be47d55a#diff-c71d1ec016afd364224d9cd82214ae31

2020-06-11 02:30 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/BodyConverter.java
> +     * @return ボディを表す文字列
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/a34a6855a509aeef0e7355d5aa097049be47d55a#diff-103bfda101b859c7ce20541f451869daR22

2020-06-11 02:30 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +    public MediaType getMediaType() {
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/a34a6855a509aeef0e7355d5aa097049be47d55a#diff-57b42d271df0c95b023bff9b4d1a28f7R71

2020-06-11 02:31 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/JacksonBodyConverter.java
> +    public static final MediaType CONVERTIBLE_TYPE = new MediaType("application/json");
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/0d76d1ae4243abdadf426e40b13e910741a8b9e2#diff-6821d0512639d6384a9819f9d41f79d8R12

2020-06-11 02:32 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/JacksonBodyConverter.java
> +        configure(objectMapper);
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/0d76d1ae4243abdadf426e40b13e910741a8b9e2#

2020-06-11 02:37 UTC, kumagoro1202 commented
MockHttpRequestのsetterについて追加で3つオーバーライドしました。
bodyReaderだけは、コンストラクタでしか使用されずそもそもアクセサがあること自体に違和感があります。利用者が使う場面はないのでオーバーライドしていません。

https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/7728b3dd59b3e1716d855088edd4419e8cba6b2f

2020-06-11 04:10 UTC, kumagoro1202 commented
> toString内でURLを組み立てていますが、その後にjava.net.URI.toASCIIStringしたらもっと楽になりそうだと思ったんですが、どうですか？
POSTのリクエストボディにFormを入れる際にう`URI`クラスで`toASCIIString()`しても問題ないですか？挙動としては想定通りですが、"URI"クラスというのが気になりました。

https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/5fa41fdd375840f5d6ea62cddf5dfb21e30fa851

2020-06-11 07:20 UTC, backpaper0 requested changes

2020-06-11 07:20 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +        getHeaderMap().put("Content-Type", contentType);
Content-Lengthと同様に定数化しましょう。

2020-06-11 07:20 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +    public static final String CONTENT_LENGTH_KEY = "Content-Length";
privateにしましょう。

2020-06-11 07:20 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +            String contentLengthOrg = headers.get(CONTENT_LENGTH_KEY);
`Org`って何を表していますか？（パッと思いつくのはOrganization）

2020-06-11 07:20 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +     * リクエストパラメータのMapをURLエンコードし結合する。
URLエンコードは別の場所で行うようにしましたよね。

2020-06-11 07:20 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/MediaType.java
> +        mediaType = parts[0].trim().toLowerCase();
`new MediaType("    ")`や`new MediaType ("    ;    ")`みたいな不正なインスタンスを作れますね。

2020-06-11 08:14 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/MediaType.java
> +        mediaType = parts[0].trim().toLowerCase();
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/44132e475a65331a0a32130a8c14565b9cfa856b

2020-06-11 08:15 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +        getHeaderMap().put("Content-Type", contentType);
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/ed1130d2e36766b1f922531840d59f1e32f2ed9d#diff-57b42d271df0c95b023bff9b4d1a28f7R28

2020-06-11 08:15 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +    public static final String CONTENT_LENGTH_KEY = "Content-Length";
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/ed1130d2e36766b1f922531840d59f1e32f2ed9d#diff-57b42d271df0c95b023bff9b4d1a28f7R30

2020-06-11 08:16 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +            String contentLengthOrg = headers.get(CONTENT_LENGTH_KEY);
originalのつもりでしたがわかりにくいので名前を変えました。
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/ed1130d2e36766b1f922531840d59f1e32f2ed9d#diff-57b42d271df0c95b023bff9b4d1a28f7R198

2020-06-11 08:16 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +     * リクエストパラメータのMapをURLエンコードし結合する。
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/ed1130d2e36766b1f922531840d59f1e32f2ed9d#diff-57b42d271df0c95b023bff9b4d1a28f7R210

2020-06-11 08:43 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +            String contentLengthOrg = headers.get(CONTENT_LENGTH_KEY);
あー、なるほど！

だったら`contentLengthFromHeader`とかで良いんじゃないかな。

2020-06-11 08:46 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/RestMockHttpRequest.java
> +     * リクエストパラメータのMapをURLエンコードし結合する。
`@return`のコメントが直っていないです。
1つの指摘に対して関連しそうなところは探す癖をつけよう。

2020-06-11 08:48 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/MediaType.java
> +        mediaType = parts[0].trim().toLowerCase();
`parts[0].trim()`を2度も行っているので一度変数へ格納するようにしてください。

これは指摘に対して場当たり的に対応しているように見えます。
対応をしたらリファクタリングの余地がないか周辺のコードを確認する癖をつけましょう。

2020-06-11 08:49 UTC, backpaper0 requested changes
確認しました。

2020-06-12 04:28 UTC, backpaper0 approved these changes

2020-06-17 08:03 UTC, merged