Cookie引き回し用のRequestResponseProcessorを実装しました
nablarch/nablarch-testing-rest pull request #34
Opened 2023-05-24 00:53 UTC by chupaaaaaaan

2023-05-25 06:16 UTC, kumagoro1202 requested changes

2023-05-25 06:16 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/NablarchSIDManager.java
> +        super.setCookieName("NABLARCH_SID");
NABLARCH_SIDは固定値ではなく設定で変更できます。
https://nablarch.github.io/docs/LATEST/doc/application_framework/application_framework/handlers/web/SessionStoreHandler.html#id
この実装では名前を変えた時に引き継げなくなってしまいます。

2023-05-25 06:16 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/RequestResponseCookieManager.java
> +            if (cookie.getDelegateMap().containsKey(cookieName)) {
MapWrapperがcontainsKeyをオーバーライドしているのでgetDelegateMap()の呼び出しは不要です。

2023-05-25 06:16 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/RequestResponseCookieManager.java
> +                cookieValue = cookie.getDelegateMap().get(cookieName);
同上。getDelegateMap()は不要

2023-05-29 03:42 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/NablarchSIDManager.java
> +        super.setCookieName("NABLARCH_SID");
実装修正しました。
また、名前変更確認のテストを追加しました（元のテストから復活させました）

2023-05-29 03:42 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/RequestResponseCookieManager.java
> +            if (cookie.getDelegateMap().containsKey(cookieName)) {
修正しました。

2023-05-29 03:42 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/RequestResponseCookieManager.java
> +                cookieValue = cookie.getDelegateMap().get(cookieName);
修正しました。

2023-06-06 04:21 UTC, kumagoro1202 requested changes

2023-06-06 04:21 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/http/ComplexRequestResponseProcessorTest.java
> +        httpCookie.getDelegateMap().put("NABLARCH_SID", "nablarch_sid");
getDelegateMapは不要。

2023-06-06 04:21 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/http/ComplexRequestResponseProcessorTest.java
> +        HttpCookie httpCookie = new HttpCookie();
`response.setHeader("Set-Cookie", "NABLARCH_SID=nablarch_sid");`は不要では。

2023-06-06 04:21 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/http/RequestResponseCookieManagerTest.java
> +            System.setOut(new PrintStream(onMemoryOut, true, "UTF-8"));
標準出力を切り替えているのは何のため？

2023-06-06 06:00 UTC, chupaaaaaaan commented on src/test/java/nablarch/test/core/http/ComplexRequestResponseProcessorTest.java
> +        httpCookie.getDelegateMap().put("NABLARCH_SID", "nablarch_sid");
いずれも削除しました。

2023-06-06 06:01 UTC, chupaaaaaaan commented on src/test/java/nablarch/test/core/http/ComplexRequestResponseProcessorTest.java
> +        HttpCookie httpCookie = new HttpCookie();
元々のテストにあったものを踏襲して記載しましたが、今回の変更でクッキーを取得する方法を変更したことで、むしろこの行が存在しているのが不適切と認識しました。
`setHeader()` をしている箇所をいずれも削除しました。

2023-06-06 06:02 UTC, chupaaaaaaan commented on src/test/java/nablarch/test/core/http/RequestResponseCookieManagerTest.java
> +            System.setOut(new PrintStream(onMemoryOut, true, "UTF-8"));
不要だったので削除しました。

2023-06-06 09:15 UTC, kumagoro1202 requested changes

2023-06-06 09:15 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/http/ComplexRequestResponseProcessorTest.java
> +
NABLARCH_SIDをresponseに設定する処理がなくなってます。

2023-06-06 09:48 UTC, chupaaaaaaan commented on src/test/java/nablarch/test/core/http/ComplexRequestResponseProcessorTest.java
> +
修正しました。

2023-06-07 02:37 UTC, kumagoro1202 approved these changes

2023-06-07 02:37 UTC, merged