NTFでCookie引継ぎ可にする対応で、インスペクションの警告を修正
nablarch/nablarch-testing-rest pull request #36
Opened 2023-09-11 10:51 UTC by chupaaaaaaan

2023-09-12 05:36 UTC, kumagoro1202 requested changes

2023-09-12 05:36 UTC, kumagoro1202 commented on src/test/java/nablarch/fw/web/RestMockHttpRequestTest.java
> +    @SuppressWarnings("deprecation")
これはJakartaEE10対応版ではassertThrowsに変えたいのでsuppressせずに無視してください。

2023-09-12 05:36 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/http/RequestResponseCookieManagerTest.java
> +    @SuppressWarnings("deprecation")
同上

2023-09-14 01:50 UTC, chupaaaaaaan commented on src/test/java/nablarch/fw/web/RestMockHttpRequestTest.java
> +    @SuppressWarnings("deprecation")
修正しました（下の修正と合わせて実施）

229925836a5e2b6897fcf30461710ff007b18150

2023-09-14 01:50 UTC, chupaaaaaaan commented on src/test/java/nablarch/test/core/http/RequestResponseCookieManagerTest.java
> +    @SuppressWarnings("deprecation")
修正しました（上の修正と合わせて実施）

229925836a5e2b6897fcf30461710ff007b18150

2023-09-14 04:38 UTC, merged